# Generated by Django 2.1.5 on 2019-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190318_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
